### ISSUE TITLE
boneco novo

### ISSUE THREAD

**Issue by Marthiins** [Marthiins/Marthiins#2]

**Comment by Marthiins** [comment]
![download20220906195914](https://user-images.githubusercontent.com/47826754/188290184-98c0b53c-1ecb-420d-bc1d-162b0e2a9c2e.png)

**Comment by Marthiins** [comment]
![download20220901002501](https://user-images.githubusercontent.com/47826754/188355031-67873aa4-100a-4a50-8ea9-33165f63bd94.png)

**Comment by AriHenrique** [comment]
![remove](https://user-images.githubusercontent.com/97318481/188356407-66656a55-42ab-4be7-bf1b-6cdb62c4ddc6.png)
so usar esse

**Comment by Marthiins** [comment]
![download20220901005317](https://user-images.githubusercontent.com/47826754/188357708-748fc4f4-5846-47a3-9063-ce04eeefcb8f.png)

**Comment by Marthiins** [comment]
finish

**Comment by Marthiins** [comment]
finish
